type: object
properties:
  id:
    type: int
    description: The unique identifier for the user.
  gender:
    type: enum
    description: The gender of the user.
    enum:
      - "Homme"
      - "Femme"
      - "Autre"
    required: true
  firstName:
    type: string
    description: The first name of the user.
    required: true
  lastName:
    type: string
    description: The last name of the user.
    required: true
  profileImage:
    type: string
    description: The profile image of the user.
    required: true
  phone:
    type: string
    description: The phone of the user.
    required: true
  adressLine:
    type: string
    description: The adress line of the user.
    required: true
  state:
    type: string
    description: The state of the user.
    required: true
  city:
    type: string
    description: The city of the user.
    required: true
  postalCode:
    type: string
    description: The postal code of the user.
    required: true
  country:
    type: string
    description: The country of the user.
    required: true
  dateOfBirth:
    type: string
    format: date
    description: The date of birth of the user.
    required: true
  lastSearch:
    type: string
    description: The last search of the user.
    required: true