trigger:
  branches:
    include:
    - dev

pr: none

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: './apps/ytravel-backend/Dockerfile'
        tags: |
          $(tag)

- stage: Deploy
  displayName: Deploy to Azure App Service
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployToAzure
    displayName: Deploy to Azure
    environment: 'developpement'
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Azure for Students(5de54548-ddbe-406e-a1d2-d64d7ba823d4)'
              appType: 'webAppContainer'
              WebAppName: 'ytravel-backend'
              DockerImageTag: '$(tag)'
