trigger:
  branches:
    include:
    - dev

pr: none

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: 'd591abad-c6b1-49f5-a112-db34c8d0d7bb'
  imageRepository: 'ytravelorganisationbackend'
  containerRegistry: 'ytravelregistry.azurecr.io'
  dockerfilePath: './apps/ytravel-backend/'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push Image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: $(dockerRegistryServiceConnection)

    - task: Docker@2
      displayName: Build and push an image
      inputs:
        command: buildAndPush
        repository: $(containerRegistry)/$(imageRepository)
        dockerfile: $(dockerfilePath)Dockerfile
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

- stage: Deploy
  displayName: Deploy to Azure App Service
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployToAzure
    displayName: Deploy to Azure
    environment: 'production' # Adjust as needed
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Azure for Students(5de54548-ddbe-406e-a1d2-d64d7ba823d4)'
              appType: 'webAppContainer'
              WebAppName: 'ytravel-backend'
              DockerNamespace: $(containerRegistry)
              DockerRepository: $(imageRepository)
              DockerImageTag: '$(tag)'