version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ytravel_db_user
      POSTGRES_PASSWORD: ytravel_db_password
      POSTGRES_DB: YTravel
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ytravel-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    environment:
      REDIS_PASSWORD: ytravel_redis_password
    networks:
      - ytravel-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - ytravel-network

networks:
  ytravel-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
