FROM node:18 AS build
WORKDIR /app
COPY package.json /app
RUN npm install

FROM build AS base
COPY . .
RUN npx prisma generate
RUN chmod +x build-all.sh
RUN ./build-all.sh

FROM base AS dbgenerator
CMD ["npx", "prisma", "db", "push"]


FROM node:18 as smtp
WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npx prisma generate
RUN npm run build

EXPOSE 3000
CMD ["npm", "run", "start:dev", "smtp"]

FROM node:18-slim AS ytraveling
WORKDIR /app
COPY package*.json ./

RUN npm install
COPY . .

RUN npx prisma generate
RUN npm run build

EXPOSE 3000
CMD ["npm", "run", "start:dev", "ytraveling-backend"]
