version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ytravel_db_user
      POSTGRES_PASSWORD: ytravel_db_password
      POSTGRES_DB: YTravel
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ytravel-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    environment:
      REDIS_PASSWORD: ytravel_redis_password
    networks:
      - ytravel-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - ytravel-network

  app:
    build: .
    ports:
      - "3000:3000"
    networks:
      - ytravel-network
    depends_on:
      - postgres
      - redis

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - ytravel-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - ytravel-network
    depends_on:
      - postgres
      - redis
      - mailhog

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3001:3000"
    networks:
      - ytravel-network
    depends_on:
      - prometheus

networks:
  ytravel-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  grafana_data: